### ISSUE TITLE
1. DSA Lecture: on OOPS by Kunal K

### ISSUE THREAD

**Issue by Vishwajeet-29-pro** [Vishwajeet-29-pro/JavaDSA#2]

**Comment by VishwajeetVT** [comment]
Covered packages, static keyword, inner classes and Singleton class.

**Comment by Vishwajeet-29-pro** [comment]
Reopen DSA Lecture (for 16 Nov)
Complete at least one hour Lecture

**Comment by VishwajeetVT** [comment]
Completed Tutorial up to targeted time.
Cover topics like Inheritance, super keyword, private keyword, Single Inheritance.
